# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://PCsforB40.github.io
title: PCs for B40
description: An initiative between Manipal International University (MIU) and Heriot-Watt University Malaysia (HWUM) students
to crowdfund for PCs components and assemble the PCs, to donate to B40 students in need.
copyright: 'Copyright &copy; 2022 PCs for B40. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://www.instagram.com/pc4b40/
  - title: linkedin
    url: https://www.linkedin.com/company/pcs-for-b40
